In [29]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [30]:
df = pd.read_csv("D:\AML_lab\data\Data.csv")
df

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [31]:
df.shape

(10, 4)

In [32]:
df.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='str')

In [33]:
df.dtypes

Country          str
Age          float64
Salary       float64
Purchased        str
dtype: object

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     str
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     str
dtypes: float64(2), str(2)
memory usage: 452.0 bytes

In [35]:
df.describe()

             Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [36]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [37]:
df.duplicated().sum()

np.int64(0)

In [38]:
#split indepedent variable
df
x=df.iloc[:, :-1].values
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [39]:
#dpilt dependent variable
y=df.iloc[:,3].values
y

<StringArray>
['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
Length: 10, dtype: str

In [40]:
#taking care of missing data
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values = np.nan, strategy ='mean')
imputer =imputer.fit(x[:,1:3])
x[:,1:3] =imputer.transform(x[:,1:3])
x
#Nan is for the numerical data col

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [41]:
#encoding the categoricaL data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X=LabelEncoder()
x[:,0]=labelencoder_X.fit_transform(x[:, 0])
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [ ]:
from sklearn.compose import ColumnTransformer 

ct= ColumnTransformer([("Country", OneHotEncoder(),[0])], remainder = "passthrough")
x=ct.fit_transform(x)

x.astype(int)

array([[    1,     0,     0,    44, 72000],
       [    0,     0,     1,    27, 48000],
       [    0,     1,     0,    30, 54000],
       [    0,     0,     1,    38, 61000],
       [    0,     1,     0,    40, 63777],
       [    1,     0,     0,    35, 58000],
       [    0,     0,     1,    38, 52000],
       [    1,     0,     0,    48, 79000],
       [    0,     1,     0,    50, 83000],
       [    1,     0,     0,    37, 67000]])

In [43]:
#Encoding the Dependent variable
labelencoder_y =LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
#split the data into training and testing
#test_size=0.2 -> training 80%, testing %20
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=45)
#X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
X_test
#X_test.astype(int)

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778]], dtype=object)

In [46]:
X_train

array([[0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0]], dtype=object)

In [47]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [48]:
X_test

array([[-1.        ,  2.64575131, -0.77459667, -1.39625191, -0.93979342],
       [-1.        ,  2.64575131, -0.77459667,  0.03989291, -0.10442149]])

In [49]:
X_train

array([[-1.        , -0.37796447,  1.29099445, -1.82709535, -1.45240802],
       [-1.        ,  2.64575131, -0.77459667,  1.47603773,  1.53784378],
       [ 1.        , -0.37796447, -0.77459667, -0.39095053,  0.17087153],
       [-1.        , -0.37796447,  1.29099445, -0.1356359 , -1.11066496],
       [ 1.        , -0.37796447, -0.77459667, -0.6781795 , -0.59805036],
       [ 1.        , -0.37796447, -0.77459667,  1.18880877,  1.19610072],
       [ 1.        , -0.37796447, -0.77459667,  0.61435084,  0.59805036],
       [-1.        , -0.37796447,  1.29099445, -0.24733605, -0.34174306]])